#+title: Todo


* Jury potentiel
** Dates
Envoi du manuscript fin mars. Dernière semaine de mars ? -> vendredi 31 mars.
Envoi du rapport, 1 mois plus tard (fin avril). À vérifier avec l'ED.
Soutenance, 1 mois plus tard (fin mai). À vérifier avec l'ED
** TODO Envoyer mail ED pour confirmer jury
** TODO Envoyer mail demande au jury
donner les dates (envoi manuscript, envoi rapport)
+doodle pour la date de soutenance
** Liste
*** Daniele Iudicone
Departement of Integrated Marine Ecology, Stazione Zoologica Anton Dohrn, Napoli (SZN)
mail:daniele.iudicone@szn.it
orcid:0000-0002-7473-394X
site:https://www.szn.it/index.php/it/personale/staff/103-iudicone-daniele/765-iudicone-daniele
Équivalence ?
Rapporteur ?
*** Fabrizio d'Ortenzio
Laboratoire Océangraphique de Villefranche (LOV)
mail:fabrizio.dortenzio@imev-mer.fr
site:https://lov.imev-mer.fr/web/member/fabrizio-dortenzio/
DR CNRS, Hdr
Rapporteur (je sais pas si LOV est considéré comme SU) ?
*** Aida Alvera-Azcárate
Université de Liège, Faculté des Sciences:
- Département d'Astrophysique, Géophysique et Océanographie (AGO)
- GeoHydrodynamics and Environment Research (GHER)
- Freshwater and OCeanic science Unit of ReSearch (FOCUS)
mail:a.alvera@uliege.be
site:https://www.uliege.be/cms/c_9054334/en/directory?uid=U205291
orcid:0000-0002-0484-4791
Équivalence ? Rapportrice ?
*** Marie Isabelle Pujol
CLS, Environment and Climate Monitoring
*** Sakina-Dorothée Ayata
LOCEAN/IPSL
Maîtresse de conférences HDR
*** Lars Stemmann
Professeur Sorbonne Université, LOV
Président du jury ?
mail:lars.stemmann@imev-mer.fr
site:https://lov.imev-mer.fr/web/member/lars-stemmann/
orcid:0000-0001-8935-4531
*** Hubert Loisel
Université du Littoral Côte d'Opale (ULCO)
Laboratoire d'Océanologie et de Géosciences (LOG)
site:https://www.researchgate.net/profile/Hubert-Loisel
mail:hubert.loisel@univ-littoral.fr
Équivalence ?
Rapporteur ?
*** Roy El Hourany
ULCO - LOG
site:https://www.researchgate.net/profile/Roy-El-Hourany
mail:roy.elhourany@locean.ipsl.fr
mail:roy.elhourany@univ-littoral.fr ?
orcid:0000-0002-6454-1645
Chercheur junior CNRS

* Administratif
** TODO Valider l'enseignement :(

* Inbox
** je ou nous ?
** Réanalyses -> renommer Mercator
** Ajouter figure comparaison Chl GlobColour / MODIS
** Commandes gls
je suis frileux quand j'utilise des abbrv dans une phrase à propos de l'article qui précède.
Par ex. on a "le HI" et "l'heterogeneity index" :/
ça serait pas mal d'avoir une commande qui gère ça
** Plot exemples
numérotation (1a) -> (a1)
** Durée bloom marker plus jolis
markeredgecolor and stuff
faire un plot légèrement plus petit aussi
** Réduire marges
visiblement on est autour de 90 caractères. C'est trop (conseillé 45-70, idéal 66)
** small caps on acronyms
because it's nice 😊

* Recommendations de style
** GLS
On se dit que pas de \ab ?
Ou alors \ab est fixé. (soit tout le temps court soit tout le temps long, pas de first-use)
*** Titres et Captions
Ne pas mettre de commandes dans les titres de section.
Dans les titres de caption, utiliser glsentryshort
Dans les captions, open bar (a priori).
** Figures
Toujours centrées.
Utiliser captionT{titre}{caption}. Le titre sera mis dans la ToF et ajouté en emph au début de la caption.
** Cross refs
*** abbrv
pas d'abbréviations quand c'est dans la phrase.
On voit sur la figure~\ref{}. On a ce résultat~(\cref{}).
De manière générale éviter de ref les figures dans le cours de la phrase de toute façon.

Pour les sections, \cref n'
** Citations
*** Articles
use \textcite and (\cite)
\parencite (voir même \autocite) est généralement préféré, mais:
- je suis à peu près sur de conserver ce schéma
- au pire, ça se modifie sans trop de soucis avec Emacs
- a priori, je n'ai pas de différence de style entre \cite et \parencite
Et surtout, je trouve ça beaucoup plus clair dans le texte. Ça devrait m'aider à repérer les ~ manquants.
*** Datasets
use \footfullcite
*** Software
use \citesoft
** Punctuations
*** parenthèses
*** tirets en incise
use \encadra{}, ça utilise des tirets cadratins.
Si la phrase se termine par un tiret, alors utiliser \encadra*{}.
*** Tirets
Pour mettre un tiret dans un mot préférer "-. Cela permet d'avoir un mot breakable (y compris au tiret).
Pour mettre un tiret non-breakable, utiliser "~. Utile pour les acronymes notamment.
*** citations (quotations)
utiliser \guil{} pour des guillements français.
\guil*{} pour des guillements anglais (pour signaler un manque d'exactitude, les guillements des doigts quoi).
** Insertions d'anglais
Pour insérer des mots anglais préférer utiliser \eng{}. Cela change les options de biblatex et autres paquets compatibles. C'est surtout utile pour adapter le setup d'hyphenation.

Pour signaler une traduction de l'anglais utiliser \engquote{} (met l'expression entre guillemets).
** Non breaking spaces
Attention si l'élement est multiple.
les équations 2 et~3.
le truc~T de longueur 2~ou plus.
*** (cross-)references
refname~\ref,
avant une ref ou une citation, seulement si entre parenthèses / pas dans le flow de la phrase:
On voit tel résultat~(\cite{whatev_2000}).
On voit tel résultat~(\cref{fig:whatev}).
Mais: On voit sur la \crefname{fig:whatev}.
*** Au milieu des noms
Donald~E. Knuth. Machin Van~der~Truk.
Utiliser \bname pour ça.
*** Entre un nombre et son unité
3~jours.
*** Nombre dans une phrase
~\num, ~\ang, ~\qty,...
Même entre parenthèses: telles valeurs~(\qty{})
*** mathematical symbol à côté de son nom
l'écart"-type~\ab{std}
tel truc~\(T\)
Cela vaut pour les abbréviations \al{hi}~(\as{hi})
Autres cas: produits~L2
*** Symbole à côté de préposition
de~x, from 0 to~1, increase by~2.
Attention encore aux compositions: de u~et~v.
*** Équations en phrases
est égal à~2, moins que~x, pour tout~i.
*** numbers, quantities
~\num, ~\qty
*** Quand des cas sont énumérés
Sont graphés la sst~(a) et la chl~(b).
Ces cas sont (1)~isolés, (2)~rares.
*** Dans les explications de figures
quand on fait référence à qq chose sur la figure
par exemple: Est tracé la température seuil~(trait rouge).
Ça évite d'avoir un orphelin loin de sa ref.
** Énumérations
Préférer comme une phrase, avec des virgules (ou point-virgules), et un point final.
Le et final peut être omis pour plus de lisibilité si les items s'alignent.
\item a,
\item b,
\item (et) c.
** Majuscules
https://fr.wikipedia.org/wiki/Usage_des_majuscules_en_fran%C3%A7ais
*** En fr. pas de maj pour les jours de la semaine, les mois.
*** aux gentilés, mais pas aux noms de langues, ou si utilisé comme adj
c'est un Français, il parle le français
la région parisienne
*** Antonomase, pas de maj
fonction gaussienne.
*** points cardinaux, pas maj sauf si toponyme
le sud de l'Amérique, l'Amérique du Sud
l'hémisphère nord
exception: le pôle Nord
**** usage alternatif
selon certain, si cela sert à désigner une partie de la terre une majuscule est ok: hémisphère Nord, l'Atlantique Nord
Je préfère celle-ci en vrai, proche de l'anglais

* Vérifications à faire
** Spelling
** Regexps
#+begin_src
Repeated words
\<\(\w+\)\>\s-+\<\1\>

Double espaces (ceux là normalement c'est pas grave)
\>\s-\{2,\}

Espaces avant/après énumérations
\s-?([a-z])\s-?

Espaces avant commandes de cross-ref
\s-[(]?\\\(cref\|Cref|ref\)

Espaces avant inline maths
\s-[(]?\\(

Tirets normaux
[[[[:alpha:]]]]-[[[[:alpha:]]]]

Espaces avant commandes. Ajouter à l'option Linker de ChkTeX ce qu'il faut.
\parencite
\parenref

#+end_src
