#+title: Todo


* Jury potentiel
** Dates
Envoi du manuscript fin mars. Dernière semaine de mars ? -> vendredi 31 mars.
Envoi du rapport, 1 mois plus tard (fin avril). À vérifier avec l'ED.
Soutenance, 1 mois plus tard (fin mai). À vérifier avec l'ED
** Dispo

*** tentative recap
JUIN
19 xHubert
20 xHubert
21 xLars
22 xLars xHubert
23 xLars xHubert
--
26 xLars (Hubert:visio)
27 xLars xHubert
28 xLars xAida
29 xLars xAida xÉlodie
30 xÉlodie (Aida:aprem si besoin)

JUILLET
 3 (Hubert:visio) <-
 4 (Hubert:visio) <-
 5 xHubert
 6 xHubert xAida
 7 xHubert xAida
--
10 xHubert
11 xHubert
12 xHubert
13 xHubert xÉlodie
14 xHubert xÉlodie

*** Hubert:
- Juin 21
- Juin 26 (matin en visio)
- Juin 28
- Juin 29 (matin en visio)
- Juin 30
- Juillet 3 (visio, avant 18h)
- Juillet 4 (visio, avant 18h)
*** Daniele
Dispo <3
*** Élodie
26-28 juin, 3-7 juillet
si jamais, du 19 au 23 juin et du 10 au 12 juillet
*** Lars
pas dispo du 21 au 29 juin (peut être même jusqu'à plus tard)
*** Aida
19-23 juin, 26-27 juin, 30 juin aprem si besoin,
3-5 juillet, 10-14 juillet
** Liste
*** OKAY Daniele Iudicone
Departement of Integrated Marine Ecology, Stazione Zoologica Anton Dohrn, Napoli (SZN)
mail:daniele.iudicone@szn.it
orcid:0000-0002-7473-394X
site:https://www.szn.it/index.php/it/personale/staff/103-iudicone-daniele/765-iudicone-daniele
Équivalence ?
*** NO Fabrizio d'Ortenzio
Laboratoire Océangraphique de Villefranche (LOV)
mail:fabrizio.dortenzio@imev-mer.fr
site:https://lov.imev-mer.fr/web/member/fabrizio-dortenzio/
DR CNRS, Hdr
*** OKAY Aida Alvera-Azcárate
Université de Liège, Faculté des Sciences:
- Département d'Astrophysique, Géophysique et Océanographie (AGO)
- GeoHydrodynamics and Environment Research (GHER)
- Freshwater and OCeanic science Unit of ReSearch (FOCUS)
mail:a.alvera@uliege.be
site:https://www.uliege.be/cms/c_9054334/en/directory?uid=U205291
orcid:0000-0002-0484-4791
Équivalence ? Rapportrice !
*** OKAY Élodie Martinez
LOPS
mail:elodie.martinez@ird.fr
site:https://emartinez550.wixsite.com/website/professional-experience
*** NO Marie Isabelle Pujol
CLS, Environment and Climate Monitoring
*** NO Sakina-Dorothée Ayata
LOCEAN/IPSL
Maîtresse de conférences HDR
*** OKAY Lars Stemmann
Professeur Sorbonne Université, LOV
Président du jury ?
mail:lars.stemmann@imev-mer.fr
site:https://lov.imev-mer.fr/web/member/lars-stemmann/
orcid:0000-0001-8935-4531
*** OKAY Hubert Loisel
Université du Littoral Côte d'Opale (ULCO)
Laboratoire d'Océanologie et de Géosciences (LOG)
site:https://www.researchgate.net/profile/Hubert-Loisel
mail:hubert.loisel@univ-littoral.fr
Équivalence ?
Rapporteur !
*** NO Roy El Hourany
ULCO - LOG
site:https://www.researchgate.net/profile/Roy-El-Hourany
mail:roy.elhourany@locean.ipsl.fr
mail:roy.elhourany@univ-littoral.fr ?
orcid:0000-0002-6454-1645
Chercheur junior CNRS

* Administratif
** TODO Valider l'enseignement :(

* Inbox
** Quel est le timerange des produits que j'utilise ?
** Envoi du manuscrit
- 2 mails séparés aux rapporteurs et examinateurs
- demander si ils veulent une version papier
- bien préciser aux rapporteurs qu'il y a une date limite pour envoyer leurs rapports, et qu'ils vont aussi recevoir un mail officiel de l'ed un peu plus tard
*** mail rapporteurs
Bonjour,

Encore une fois, je vous remercie d'avoir accepté d'examiner mon manuscrit.
Vous pourrez le trouver ci-joint en format PDF. N'hésitez pas à me contacter si vous rencontreriez des problèmes techniques pour le lire. Si vous le souhaitez, je peux également vous envoyer une version papier. Dans ce cas-là, veuillez m'indiquer l'adresse à laquelle vous souhaiteriez le recevoir.

L'école doctorale attend que vous envoyiez votre rapport 4 semaines avant la soutenance, c'est-à-dire avant le 6 juin. Vous devriez recevoir sous peu plus d'informations de la part de l'école doctorale.

J'en profite pour vous informer que Pascale Bouruet-Aubertot a accepté d'être présidente du jury, et je l'en remercie. Nous vous confirmons donc que la soutenance aura bien lieu mardi 4 juillet après-midi, à Paris (avec visio).

Bien cordialement,

*** mail jury
Cher jury,

Vous pourrez trouver ci-joint mon manuscrit de thèse en format PDF, qui vient d'être envoyé aux rapporteurs. N'hésitez pas à me contacter si vous rencontreriez des problèmes techniques pour le lire. Si vous le souhaitez, je peux également vous envoyer une version papier. Dans ce cas-là, veuillez m'indiquer l'adresse à laquelle vous souhaiteriez le recevoir.

J'en profite pour vous informer que Pascale Bouruet-Aubertot a accepté d'être présidente du jury, et je l'en remercie. Nous vous confirmons donc que la soutenance aura bien lieu mardi 4 juillet après-midi, à Paris (avec visio).

Bien cordialement,


* Résumés
** Fr
À la base de la chaîne trophique dans les océans se trouve le phytoplancton: un ensemble de micro-organismes créant de la matière organique à partir du carbone dissous, de nutriments, et de lumière. Les courants océaniques affectent la croissance du phytoplancton de différentes manières. En particulier, les structures (dites de submésoéchelle) à des échelles comprises entre 1 et 10 km, et évoluant sur des temps caractéristiques allant du jour à la semaine, jouent un rôle important pour le paysage biogéochimique des océans. Du fait de leur taille et leur temps de vie caractéristiques réduits, elles sont cependant difficiles à observer -à la fois par mesures in situ et par satellite- et à représenter correctement dans les modèles numériques.

Nous nous penchons sur deux effets des fronts de densité à ces échelles. Ces derniers génèrent des circulations secondaires verticales, dont la branche ascendante peut remonter des nutriments depuis les eaux profondes vers les eaux ensoleillées de surface. Cet apport local de nutriment, et l'augmentation de productivité qui s'ensuit, a largement été observé, mais la quantification de son impact global n'est pas encore bien établi. Ces fronts tendent également à favoriser, toujours localement, la restratification des eaux de surface. Des modèles numériques ont montré que ce processus pouvait occasionner des blooms printaniers plus précoces.

Dans cette thèse, nous utilisons 20 années d'images satellitaires afin de mieux quantifier ces effets dans la région entourant le Gulf Stream. À partir de la température de surface satellite (SST) nous calculons un indice d'hétérogénéité (HI) afin de détecter les fronts, et les séparer en fronts faibles (ceux de submésoéchelle, éphémères) et fronts forts. Nous séparons la région en trois biomes: subtropicaux permanent et saisonnier, et subpolaire.

Nous comparons les valeurs de chlorophylle-a (Chl-a) à l'extérieur et dans les fronts (faibles et forts). Nous constatons que les fronts faibles sont associés à un excès local de Chl-a moins important que les fronts forts, mais du fait de leur ubiquité le surplus de Chl-a qu'ils induisent à l'échelle du biome est comparable. L'excès local de Chl-a dans les fronts est 2 à 3 fois plus important dans le biome subpolaire que dans la région oligotrophe. Malgré des impacts spectaculaires à l'échelle locale, avec des augmentations jusqu'à de +60%, l'effet des fronts à l'échelle régionale (ie des biomes) est plus modeste, atteignant au maximum +5%.

Enfin, nous mesurons les différences dans les jours de démarrage du bloom et dans sa durée, entre les fronts et l'arrière-plan, et fournissons ainsi la première quantification par observation de cet effet. Nous constatons que la durée du bloom n'est pas significativement affectée, mais que le bloom démarre plus tôt dans les fronts, d'une à deux semaines.

Ces résultats approfondissent la quantification des impacts des courants de fines échelles sur la biogéochimie, aidant ainsi à cerner les processus déterminants et à mieux contraindre les modèles climatiques encore sujets à de fortes incertitudes en cette matière. Ce travail soulève plusieurs points clés dans l'établissement de cette quantification. Nous nous sommes uniquement penchés sur la Chl-a totale, sans examiner les réponses des différents groupes de phytoplancton, dont l'obtention des concentrations individuelles par satellite est possible. Par ailleurs, nous avons montré les contrastes régionaux existants dans une zone relativement réduite, et les difficultés liées à la découpe en biorégions homogènes. L'extension de ces résultats à d'autres régions et à l'échelle globale constitue cependant une étape future dans cet effort de quantification globale. Nous soulignons donc les défis techniques que ces perspectives impliquent, certains que nous avons rencontré dans cette étude, mais aussi les solutions que nous y avons opposées, et celles que nous pensons importantes à implémenter dans un futur proche.
** En
At the base of the food chain in the oceans is phytoplankton: a collection of microorganisms that create organic matter from dissolved carbon, nutrients, and light. Ocean currents affect the growth of phytoplankton in different ways. In particular, sub-mesoscale structures of scales of 1-10 km and evolving over characteristic times ranging from day to week, play an important role in the biogeochemical landscape of the oceans. Due to their small size and short lifetimes, they are difficult to observe -both by in situ and satellite measurements- and to represent correctly in numerical models.

Here we focus on two effects of density fronts of such scales. They generate vertical secondary circulations, whose ascending branch can potentially bring nutrients from the deep waters to the lit surface layers. This local input of nutrients, and the resulting increase in productivity, has been widely observed, but the quantification of its global impact is not yet well established. These fronts also tend, still locally, to restratify surface layers. Numerical models have shown that this process can lead to earlier spring blooms.

In this thesis, we use 20 years of satellite images to better quantify these effects in the region surrounding the Gulf Stream. From the satellite surface temperature (SST) we compute a heterogeneity index (HI) in order to detect fronts, and separate them into weak fronts (sub-mesoscale and ephemeral) and strong fronts. We separate the region into three biomes: permanent and seasonal subtropical, and subpolar.

We compare chlorophyll-a (Chl-a) values outside and inside the fronts (weak and strong). We find that weak fronts are associated with a smaller local excess of Chl-a than strong fronts, but due to their ubiquity the excess of Chl-a they induce at the scale of the biome is similar. The local excess of Chl-a in fronts is 2 to 3 times greater in the subpolar biome than in the oligotrophic region. Despite dramatic impacts at the local scale, with increases of up to +60%, the effect of fronts at the regional (i.e. biome) scale is more modest, reaching at most +5%.
Finally, we measure differences in the bloom onset and duration between the fronts and the background, and thus provide the first observational quantification of this effect. We find that the duration of the bloom is not significantly affected, but that the bloom triggers earlier in the fronts, by one to two weeks.

These results further the quantification of the impacts of fine-scale currents on biogeochemistry, thus helping to identify the significant processes and to better constrain climate models, still subject to high uncertainties in this area. This work raises several key points in the establishment of this quantification. We have focused only on total Chl-a, without examining the responses of the different phytoplankton groups, for which individual concentrations can be obtained by satellite. The extension of these results to other regions and to the global scale is however a future step in this global quantification effort. We therefore highlight the technical challenges that these perspectives imply, some of which we have encountered in this work, but also the solutions that we have used and others that we think are important to implement in the near future.
* Présentation soutenance
** idée plan
question: quels sont les impacts des fronts ?
- dans la région subtropicale (correspond au HI faible)
- dans la région Gulf Stream (correspond hi faible / fort)
- dans la région subpolaire (bloom)

* Recommendations de style
** GLS
On se dit que pas de \ab ?
Ou alors \ab est fixé. (soit tout le temps court soit tout le temps long, pas de first-use)
*** Titres et Captions
Ne pas mettre de commandes dans les titres de section.
Dans les titres de caption, utiliser glsentryshort
Dans les captions, open bar (a priori).
** Figures
Toujours centrées.
Utiliser captionT{titre}{caption}. Le titre sera mis dans la ToF et ajouté en emph au début de la caption.
** Chiffres
je crois que j'aime bien le style inline (dans le texte)
siunit insère en mode math donc c'est pas affecté.
hmmm. il y a plein d'endroits ou c'est moins adapté.
numéro de figure!, abbrev., toc!, footnotes!.
Use \textlf{} accordingly.
ça jure à côté de texte en all-caps, \abbrv{} se charge de ça.
ça jure à côté d'unités
je les laisse dans le texte quand il n'y a pas d'unités, ou qu'elles sont écrites en toutes lettres (on regarde sur 20~jours, on obtient une valeur de 0.8.)
** Cross refs
*** abbrv
pas d'abbréviations quand c'est dans la phrase.
On voit sur la figure~\ref{}. On a ce résultat~(\cref{}).
De manière générale éviter de ref les figures dans le cours de la phrase de toute façon.

Pour les sections, \cref n'abbrège pas donc on est bon.
Aussi les numéros de sections et chapitres peuvent être assez court, c'est bien d'avoir le lien hyper aussi sur le mot 'section'.
*** idée pour gérer les liens
\nref[figure]{fig:lol} => \href[fig:lol]{figure~\ref{fig:lol}}
si pas d'options -> utiliser crefname.
** Citations
*** Articles
use \textcite and (\cite)
\parencite (voir même \autocite) est généralement préféré, mais:
- je suis à peu près sur de conserver ce schéma
- au pire, ça se modifie sans trop de soucis avec Emacs
- a priori, je n'ai pas de différence de style entre \cite et \parencite
Et surtout, je trouve ça beaucoup plus clair dans le texte. Ça devrait m'aider à repérer les ~ manquants.
*** Datasets
use \footfullcite
*** Software
use \citesoft
** Punctuations
*** parenthèses
*** tirets en incise
use \encadra{}, ça utilise des tirets cadratins.
Si la phrase se termine par un tiret, alors utiliser \encadra*{}.
*** Tirets
Pour mettre un tiret dans un mot préférer "-. Cela permet d'avoir un mot breakable (y compris au tiret).
Pour mettre un tiret non-breakable, utiliser "~. Utile pour les acronymes notamment.
*** citations (quotations)
utiliser \guil{} pour des guillements français.
\guil*{} pour des guillements anglais (pour signaler un manque d'exactitude, les guillements des doigts quoi).
** Insertions d'anglais
Pour insérer des mots anglais préférer utiliser \eng{}. Cela change les options de biblatex et autres paquets compatibles. C'est surtout utile pour adapter le setup d'hyphenation.

Pour signaler une traduction de l'anglais utiliser \engquote{} (met l'expression entre guillemets).
** Non breaking spaces
Attention si l'élement est multiple.
les équations 2 et~3.
le truc~T de longueur 2~ou plus.
*** (cross-)references
toujours refname~\ref
avant une ref/citation seulement si en fin de paragraphe et pas dans le flow de la phrase.
On voit tel résultat~(\nref{fig:whatev}).\par
Mais: On voit sur la \nref[figure]{fig:whatev}.
Ça évite les orphelins en fin de phrases du style
#+begin_src
On voit très très bien ce résultat
(fig. 3).

#+end_src
*** Au milieu des noms
Donald~E. Knuth. Machin Van~der~Truk.
Utiliser \bname pour ça.
*** Entre un nombre et son unité
3~jours.
*** Nombre dans une phrase
~\num, ~\ang, ~\qty,...
pas quand entre parenthèses: telles valeurs (\qty{})
*** mathematical symbol à côté de son nom
l'écart"-type~\ab{std}
tel truc~\(T\)
Cela vaut pour les abbréviations \al{hi}~(\as{hi})
Autres cas: produits~L2
*** Symbole à côté de préposition
de~x, from 0 to~1, increase by~2.
Attention encore aux compositions: de u~et~v.
entre 0 et~15.
*** Équations en phrases
est égal à~2, moins que~x, pour tout~i.
*** Quand des cas sont énumérés
Sont graphés la sst~(a) et la chl~(b).
Ces cas sont (1)~isolés, (2)~rares.
*** Dans les explications de figures
quand on fait référence à qq chose sur la figure
par exemple: Est tracé la température seuil~(trait rouge).
Ça évite d'avoir un orphelin loin de sa ref.
** Énumérations
Préférer comme une phrase, avec des virgules (ou point-virgules), et un point final.
Le et final peut être omis pour plus de lisibilité si les items s'alignent.
\item a,
\item b,
\item (et) c.
** Majuscules
https://fr.wikipedia.org/wiki/Usage_des_majuscules_en_fran%C3%A7ais
*** En fr. pas de maj pour les jours de la semaine, les mois.
*** aux gentilés, mais pas aux noms de langues, ou si utilisé comme adj
c'est un Français, il parle le français
la région parisienne
*** Antonomase, pas de maj
fonction gaussienne.
*** points cardinaux, pas maj sauf si toponyme
le sud de l'Amérique, l'Amérique du Sud
l'hémisphère nord
exception: le pôle Nord
**** usage alternatif
selon certain, si cela sert à désigner une partie de la terre une majuscule est ok: hémisphère Nord, l'Atlantique Nord
Je préfère celle-ci en vrai, proche de l'anglais

* Vérifications à faire
** que les footnotes ne soient pas coupées
ça implique peut être de jouer avec les marges
** Regexps
#+begin_src
Repeated words
\<\(\w+\)\>\s-+\<\1\>

Double espaces (ceux là normalement c'est pas grave)
\>\s-\{2,\}

Espaces avant/après énumérations
\s-?([a-z])\s-?

Espaces avant commandes de cross-ref
\s-[(]?\\\(cref\|Cref|ref\)

Espaces avant inline maths
\s-[(]?\\(

Espaces avant commandes. Ajouter à l'option Linker de ChkTeX ce qu'il faut.
\parencite
\parenref

#+end_src
